"""Make seat_id nullable

Revision ID: 09d87bb6c65e
Revises: 38e71c4008a6
Create Date: 2025-06-15 13:41:29.291651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '09d87bb6c65e'
down_revision: Union[str, None] = '38e71c4008a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'seat_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'seat_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
