"""Add delete booking fields

Revision ID: 38e71c4008a6
Revises: fad05486b4ba
Create Date: 2025-06-13 10:21:48.731864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '38e71c4008a6'
down_revision: Union[str, None] = 'fad05486b4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('booking', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_booking_deleted'), 'booking', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_deleted'), table_name='booking')
    op.drop_column('booking', 'deleted_at')
    op.drop_column('booking', 'deleted')
    # ### end Alembic commands ###
