"""Add booking_number and drop booking_reference

Revision ID: fad05486b4ba
Revises: ce447f7199cb
Create Date: 2025-06-07 18:06:39.725428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fad05486b4ba'
down_revision: Union[str, None] = 'ce447f7199cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_booking_booking_reference', table_name='booking')
    op.create_index(op.f('ix_booking_booking_number'), 'booking', ['booking_number'], unique=True)
    op.drop_column('booking', 'booking_reference')
    op.drop_constraint('ticket_ticket_number_key', 'ticket', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ticket_ticket_number_key', 'ticket', ['ticket_number'])
    op.add_column('booking', sa.Column('booking_reference', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_booking_booking_number'), table_name='booking')
    op.create_index('ix_booking_booking_reference', 'booking', ['booking_reference'], unique=True)
    op.drop_column('booking', 'booking_number')
    # ### end Alembic commands ###
